// Rich MPWZ Union System Initial Seed Data & Settings

export const INITIAL_SYSTEM_SETTINGS = {
  union_name: "MPWZ Electricity Employees Union",
  union_short_name: "MPWZ Union",
  tagline: "Madhya Pradesh West Zone Electricity Distribution Company Official Employees & Engineers Union",
  logo_url: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=300&q=80",
  contact_email: "contact@mpwzunion.org",
  contact_phone: "+91 98260 11223",
  office_address: "Union Central Office, MPWZ Discom HQ Campus, Polo Ground, Indore, Madhya Pradesh - 452003",
  office_hours: "Monday - Saturday: 10:00 AM - 06:00 PM IST",
  registration_fee: 500,

  registration_qr_url: "/images/payment-qr.png",
  upi_id: "mpvidyut@sbi",
  account_name: "MP VIDYUT MANDAL ARAKSHIT VAR",
  
  bank_name: "State Bank of India (SBI)",
  account_number: "389201928341",
  ifsc_code: "SBIN0001234",
  payment_whatsapp_number: "+91 98260 11223",
  default_event_qr_url: "/images/payment-qr.png",
  about_summary: "Formed to uphold worker safety, fair pay scales, pension security, and technical excellence across 9 circles of Madhya Pradesh West Zone Electricity Distribution Discom.",
  social_links: {
    facebook: "https://facebook.com",
    twitter: "https://twitter.com",
    youtube: "https://youtube.com",
    whatsapp_group: "https://chat.whatsapp.com"
  }
};

export const INITIAL_USERS = [
  {
    id: 1,
    email: "admin@mpwzunion.org",
    role: "admin",
    status: "active",
    member_id: "UNION-ADMIN-001",
    profile: {
      id: 1,
      user_id: 1,
      full_name: "Er. Rajesh Sharma",
      father_husband_name: "Shri O. P. Sharma",
      dob: "1978-04-12",
      gender: "Male",
      avatar_url: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80",
      phone: "+91 98260 11223",
      whatsapp: "+91 98260 11223",
      address: "74-A, Scheme No 54, Vijay Nagar, Indore, MP",
      city: "Indore",
      district: "Indore",
      state: "Madhya Pradesh",
      pin_code: "452010",
      occupation: "Discom Service",
      company: "MP West Zone Electricity Discom",
      designation: "Executive Director / SE",
      circle: "Indore City Circle",
      union_designation: "General Secretary",
      bio: "22+ years in MP West Zone Electricity Discom. Spearheading union advocacy, safety standards for field staff, and employee pension rights.",
      emergency_contact: "+91 98260 99999",
      joining_date: "2015-01-15",
      is_public: true,
      contact_privacy: { showPhone: true, showEmail: true, showAddress: false }
    }
  },
  {
    id: 2,
    email: "sunita.chouhan@mpwzunion.org",
    role: "user",
    status: "active",
    member_id: "UNION-IND-104",
    profile: {
      id: 2,
      user_id: 2,
      full_name: "Er. Sunita Chouhan",
      father_husband_name: "Shri R. S. Chouhan",
      dob: "1983-08-24",
      gender: "Female",
      avatar_url: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=400&q=80",
      phone: "+91 98261 44556",
      whatsapp: "+91 98261 44556",
      address: "12, Saket Nagar, Indore, MP",
      city: "Indore",
      district: "Indore",
      state: "Madhya Pradesh",
      pin_code: "452018",
      occupation: "Discom Service",
      company: "MP West Zone Electricity Discom",
      designation: "Superintending Engineer (SE)",
      circle: "Indore Corporate Circle",
      union_designation: "Vice President (Women Wing)",
      bio: "Overseeing grid reliability and urban sub-station safety across Indore West Zone.",
      emergency_contact: "+91 98261 00000",
      joining_date: "2018-03-20",
      is_public: true,
      contact_privacy: { showPhone: true, showEmail: true, showAddress: true }
    }
  },
  {
    id: 3,
    email: "vikram.patel@mpwzunion.org",
    role: "user",
    status: "active",
    member_id: "UNION-UJJ-209",
    profile: {
      id: 3,
      user_id: 3,
      full_name: "Shri Vikramaditya Patel",
      father_husband_name: "Shri K. L. Patel",
      dob: "1980-11-05",
      gender: "Male",
      avatar_url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80",
      phone: "+91 94250 88776",
      whatsapp: "+91 94250 88776",
      address: "45, Freeganj, Ujjain, MP",
      city: "Ujjain",
      district: "Ujjain",
      state: "Madhya Pradesh",
      pin_code: "456010",
      occupation: "Discom Field Operations",
      company: "MP West Zone Electricity Discom",
      designation: "Line Superintendent Grade-I",
      circle: "Ujjain Circle",
      union_designation: "Zonal Secretary (Ujjain Zone)",
      bio: "18 years field experience managing 33kV & 11kV lines. Championing linemen safety gear & hazard allowances.",
      emergency_contact: "+91 94250 11111",
      joining_date: "2017-06-10",
      is_public: true,
      contact_privacy: { showPhone: true, showEmail: true, showAddress: false }
    }
  },
  {
    id: 4,
    email: "amit.joshi@mpwzunion.org",
    role: "user",
    status: "active",
    member_id: "UNION-DEW-312",
    profile: {
      id: 4,
      user_id: 4,
      full_name: "Er. Amit Joshi",
      father_husband_name: "Shri S. K. Joshi",
      dob: "1987-03-15",
      gender: "Male",
      avatar_url: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80",
      phone: "+91 94253 11224",
      whatsapp: "+91 94253 11224",
      address: "88, Civil Lines, Dewas, MP",
      city: "Dewas",
      district: "Dewas",
      state: "Madhya Pradesh",
      pin_code: "455001",
      occupation: "Discom Engineering",
      company: "MP West Zone Electricity Discom",
      designation: "Assistant Engineer (AE)",
      circle: "Dewas Division",
      union_designation: "Divisional Representative",
      bio: "Focused on smart metering infrastructure deployment, revenue protection, and union member welfare.",
      emergency_contact: "+91 94253 22222",
      joining_date: "2019-09-01",
      is_public: true,
      contact_privacy: { showPhone: true, showEmail: true, showAddress: false }
    }
  }
];

export const INITIAL_MEMBERSHIP_APPLICATIONS = [
  {
    id: 1,
    application_no: "APP-2026-081",
    full_name: "Shri Ramakant Verma",
    father_husband_name: "Shri B. L. Verma",
    dob: "1989-07-14",
    gender: "Male",
    mobile: "+91 98269 88123",
    whatsapp: "+91 98269 88123",
    email: "ramakant.verma@example.com",
    address: "Substation Colony, Scheme 78, Indore",
    city: "Indore",
    district: "Indore",
    state: "Madhya Pradesh",
    pin_code: "452010",
    occupation: "Discom Service",
    company: "MP West Zone Electricity Discom",
    designation: "Junior Engineer (JE)",
    union_info: "Looking forward to contributing to union technical welfare workshops.",
    profile_photo_url: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=400&q=80",
    identity_doc_url: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    additional_doc_url: "",
    emergency_contact: "+91 98269 00000",
    registration_fee: 500,
    payment_status: "VERIFIED",
    application_status: "PENDING",
    transaction_id: "UTR98765432101",
    payment_proof_url: "https://images.unsplash.com/photo-1559526324-4b87b5e36e44?auto=format&fit=crop&w=600&q=80",
    payment_date: "2026-09-20",
    payment_note: "Paid via GPay SBI UPI",
    created_at: "2026-09-20T10:30:00Z"
  },
  {
    id: 2,
    application_no: "APP-2026-082",
    full_name: "Er. Priyanka Sharma",
    father_husband_name: "Shri M. P. Sharma",
    dob: "1992-02-18",
    gender: "Female",
    mobile: "+91 94258 77665",
    whatsapp: "+91 94258 77665",
    email: "priyanka.sharma@example.com",
    address: "Tower 4, Green Park Colony, Ujjain",
    city: "Ujjain",
    district: "Ujjain",
    state: "Madhya Pradesh",
    pin_code: "456001",
    occupation: "Discom Testing",
    company: "MP West Zone Electricity Discom",
    designation: "Assistant Engineer (Testing)",
    union_info: "Wish to join the women's wing safety forum.",
    profile_photo_url: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=400&q=80",
    identity_doc_url: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    additional_doc_url: "",
    emergency_contact: "+91 94258 11111",
    registration_fee: 500,
    payment_status: "SUBMITTED",
    application_status: "PENDING",
    transaction_id: "UTR44332211009",
    payment_proof_url: "https://images.unsplash.com/photo-1559526324-4b87b5e36e44?auto=format&fit=crop&w=600&q=80",
    payment_date: "2026-09-22",
    payment_note: "Payment screenshot attached",
    created_at: "2026-09-22T14:15:00Z"
  }
];

export const INITIAL_EVENTS = [
  {
    id: 1,
    title: "MPWZ Union State Delegate Annual Convention 2026 (राज्य प्रांतीय अधिवेशन)",
    description: "Annual convention of MPWZ Union engineers and workers. Key agendas include OPS agitation roadmap, line safety insurance policy launch, and election of zonal body.",
    banner_url: "https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=1200&q=80",
    event_type: "CONVENTION",
    start_date: "2026-10-20",
    end_date: "2026-10-20",
    start_time: "10:00 AM",
    end_time: "05:00 PM",
    venue: "Abhay Prashal Auditorium, Race Course Road, Indore",
    address: "Race Course Road, Near High Court, Indore, MP",
    capacity: 1200,
    registered_count: 740,
    registration_start_date: "2026-09-15",
    registration_end_date: "2026-10-18",
    is_paid: true,
    event_fee: 250,
    payment_qr_url: "/images/payment-qr.png",
    payment_instructions: "Pay ₹250 via QR code or UPI (mpvidyut@sbi). Enter Transaction UTR and upload screenshot during registration.",
    whatsapp_contact: "+91 98260 11223",
    visibility: "PUBLIC",
    status: "REGISTRATION_OPEN",
    created_by: 1,
    created_at: "2026-09-10T09:00:00Z"
  },
  {
    id: 2,
    title: "Zonal Field Safety & Electrical Hazards Workshop Ujjain",
    description: "Hands-on training session for Line Superintendents, Linemen, and Testing Engineers on modern earthing rods, insulated gloves, and hot-line working safety.",
    banner_url: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&w=1200&q=80",
    event_type: "WORKSHOP",
    start_date: "2026-10-12",
    end_date: "2026-10-12",
    start_time: "11:00 AM",
    end_time: "03:00 PM",
    venue: "Vikram University Senate Hall, Ujjain",
    address: "University Campus, Kothi Road, Ujjain, MP",
    capacity: 400,
    registered_count: 310,
    registration_start_date: "2026-09-10",
    registration_end_date: "2026-10-10",
    is_paid: true,
    event_fee: 100,
    payment_qr_url: "/images/payment-qr.png",
    payment_instructions: "Registration fee ₹100 via QR (mpvidyut@sbi) includes safety kit & certificate.",
    whatsapp_contact: "+91 94250 88776",
    visibility: "PUBLIC",
    status: "REGISTRATION_OPEN",
    created_by: 1,
    created_at: "2026-09-12T10:00:00Z"
  },
  {
    id: 3,
    title: "Contract & Outsource Workers Rights & Pension Seminar",
    description: "Legal overview of labor court rulings, minimum wage guarantee, and ESIC benefits for outsourced linemen across West Zone Discom.",
    banner_url: "https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=1200&q=80",
    event_type: "MEETING",
    start_date: "2026-11-02",
    end_date: "2026-11-02",
    start_time: "02:00 PM",
    end_time: "05:00 PM",
    venue: "MPWZ Union Video Conference Portal & YouTube Live",
    address: "Online Digital Session",
    capacity: 2000,
    registered_count: 1450,
    registration_start_date: "2026-09-20",
    registration_end_date: "2026-11-01",
    is_paid: false,
    event_fee: 0,
    payment_qr_url: "",
    payment_instructions: "Free entry for all registered Union members.",
    whatsapp_contact: "+91 98260 11223",
    visibility: "MEMBERS_ONLY",
    status: "PUBLISHED",
    created_by: 1,
    created_at: "2026-09-18T14:00:00Z"
  }
];

export const INITIAL_EVENT_REGISTRATIONS = [
  {
    id: 1,
    event_id: 1,
    user_id: 2,
    pass_code: "PASS-IND-740",
    amount: 250,
    payment_status: "CONFIRMED",
    registration_status: "CONFIRMED",
    transaction_id: "UTR11223344556",
    payment_proof_url: "https://images.unsplash.com/photo-1559526324-4b87b5e36e44?auto=format&fit=crop&w=600&q=80",
    registered_at: "2026-09-21T10:00:00Z"
  }
];

export const INITIAL_PAYMENTS = [
  {
    id: 1,
    user_id: null,
    membership_application_id: 1,
    event_registration_id: null,
    payment_type: "MEMBERSHIP",
    amount: 500,
    transaction_id: "UTR98765432101",
    payment_proof_url: "https://images.unsplash.com/photo-1559526324-4b87b5e36e44?auto=format&fit=crop&w=600&q=80",
    payment_date: "2026-09-20",
    status: "VERIFIED",
    verified_by: 1,
    verified_at: "2026-09-21T11:00:00Z",
    remarks: "Verified via GPay Bank Settlement",
    created_at: "2026-09-20T10:30:00Z"
  },
  {
    id: 2,
    user_id: null,
    membership_application_id: 2,
    event_registration_id: null,
    payment_type: "MEMBERSHIP",
    amount: 500,
    transaction_id: "UTR44332211009",
    payment_proof_url: "https://images.unsplash.com/photo-1559526324-4b87b5e36e44?auto=format&fit=crop&w=600&q=80",
    payment_date: "2026-09-22",
    status: "SUBMITTED",
    verified_by: null,
    verified_at: null,
    remarks: "Submitted by applicant",
    created_at: "2026-09-22T14:15:00Z"
  },
  {
    id: 3,
    user_id: 2,
    membership_application_id: null,
    event_registration_id: 1,
    payment_type: "EVENT",
    amount: 250,
    transaction_id: "UTR11223344556",
    payment_proof_url: "https://images.unsplash.com/photo-1559526324-4b87b5e36e44?auto=format&fit=crop&w=600&q=80",
    payment_date: "2026-09-21",
    status: "VERIFIED",
    verified_by: 1,
    verified_at: "2026-09-21T10:30:00Z",
    remarks: "Event Pass Generated PASS-IND-740",
    created_at: "2026-09-21T10:00:00Z"
  }
];

export const INITIAL_ANNOUNCEMENTS = [
  {
    id: 1,
    title: "अनिश्चितकालीन कामबंद आंदोलन एवं धर्ना प्रदर्शन (Indefinite Strike & Protest Notice)",
    description: "म.प्र. पश्चिम क्षेत्र के समस्त सर्कलों (इन्दौर, उज्जैन, रतलाम, देवास, धार, खरगोन, खंडवा, मंदसौर, नीमच) के अधिकारी एवं कर्मचारी पोलो ग्राउंड इन्दौर में उपस्थित रहें। मुख्य मांगें: OPS लागू करना, संविदा लाइनमेन नियमितीकरण, एवं ₹20 लाख दुर्घटना सहायता।",
    type: "STRIKE",
    priority: "CRITICAL",
    attachment_url: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    start_date: "2026-09-22",
    expiry_date: "2026-10-10",
    target_audience: "ALL_MEMBERS",
    is_popup: true,
    status: "PUBLISHED",
    created_by: 1,
    created_at: "2026-09-22T08:00:00Z"
  },
  {
    id: 2,
    title: "Urgent Meeting regarding Safety Allowance & Linemen Gear Requisition",
    description: "All Zonal Secretaries & Executive Members are requested to join the emergency review meeting on Sunday at 11:00 AM.",
    type: "MEETING",
    priority: "HIGH",
    attachment_url: "",
    start_date: "2026-09-23",
    expiry_date: "2026-09-28",
    target_audience: "ALL_MEMBERS",
    is_popup: true,
    status: "PUBLISHED",
    created_by: 1,
    created_at: "2026-09-23T09:00:00Z"
  }
];

export const INITIAL_NOTIFICATIONS = [
  {
    id: 1,
    user_id: 1,
    announcement_id: 1,
    title: "URGENT STRIKE ALERT",
    message: "Indefinite strike notice published for Oct 05, 2026 at Polo Ground HQ Indore.",
    type: "STRIKE",
    link: "/dashboard/announcements",
    is_read: false,
    created_at: "2026-09-22T08:00:00Z"
  },
  {
    id: 2,
    user_id: 2,
    announcement_id: 1,
    title: "URGENT STRIKE ALERT",
    message: "Indefinite strike notice published for Oct 05, 2026 at Polo Ground HQ Indore.",
    type: "STRIKE",
    link: "/dashboard/announcements",
    is_read: false,
    created_at: "2026-09-22T08:00:00Z"
  }
];

export const INITIAL_UNION_STORIES = [
  {
    id: 1,
    author_id: 1,
    author_name: "Er. Rajesh Sharma",
    author_title: "General Secretary",
    author_avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80",
    title: "MPWZ Union Gazette Order 2026 — Revised DA & Grade Pay Notification",
    description: "Official Gazette circular detailing 4% Dearness Relief (DR) release and updated hazard compensation for field electrical staff across all 9 MP West Zone circles.",
    category: "Wage & Pension Orders",
    attachment_url: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    attachment_type: "PDF",
    visibility: "MEMBERS_ONLY",
    status: "PUBLISHED",
    created_at: "2026-09-18T10:00:00Z"
  },
  {
    id: 2,
    author_id: 3,
    author_name: "Shri Vikramaditya Patel",
    author_title: "Zonal Secretary (Ujjain)",
    author_avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80",
    title: "Field Safety Mandatory Protocol Handbook for 33kV & 11kV Substations",
    description: "Standard Operating Procedures for Permit-to-Work (PTW), discharge rod grounding, and transformer maintenance safety checklist.",
    category: "Safety Protocols",
    attachment_url: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    attachment_type: "PDF",
    visibility: "MEMBERS_ONLY",
    status: "PUBLISHED",
    created_at: "2026-09-15T14:30:00Z"
  }
];

export const INITIAL_SHARED_DOCUMENTS = [
  {
    id: 1,
    sender_id: 1,
    sender_name: "Er. Rajesh Sharma",
    recipient_id: 2,
    recipient_name: "Er. Sunita Chouhan",
    title: "Indore Circle Member Grievance Representation Copy",
    message: "Here is the representation document for the technical staff transfers in Indore West Division.",
    file_url: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    file_name: "Indore_Grievance_Rep_2026.pdf",
    file_type: "PDF",
    file_size: "1.4 MB",
    is_read: false,
    sent_at: "2026-09-21T16:00:00Z"
  }
];

export const INITIAL_CONTACT_SUBMISSIONS = [
  {
    id: 1,
    name: "Dinesh Kumar Yadav",
    email: "dinesh.yadav@example.com",
    phone: "+91 94255 11002",
    subject: "Inquiry regarding Union Membership Eligibility for Contract Engineers",
    message: "Respected General Secretary, I am working as contract AE in Dewas division. Am I eligible to apply for full MPWZ Union membership? Kindly confirm.",
    status: "PENDING",
    created_at: "2026-09-22T11:20:00Z"
  }
];
